name: Update Digimon README

on:
  workflow_dispatch: # Esto te agrega un botón en GitHub para correrlo cuando quieras
  schedule:
    - cron: '5 12 * * *' # Corre de forma automática y desfasada del de Pokémon

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar el script
        run: python update_digimon.py

      - name: Commitear los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "¡Nuevos Digimons en el perfil! 💻" || exit 0
          git push
