name: Update Digimon README

on:
  push:
    branches:
      - main
  schedule:
    # Lo pasamos a las 12:05 para que corra 5 minutos después y no choque con tu script de Pokémon
    - cron: '5 12 * * *' 

permissions:
  contents: write

# Esto le avisa a GitHub que si hay varias ejecuciones intentando arrancar, cancele las viejas y deje solo la última. ¡Chau conflictos!
concurrency:
  group: digimon-update
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar el script
        run: python update_digimon.py

      - name: Commitear los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "¡Nuevos Digimons en el perfil! 💻" || exit 0
          git pull --rebase origin main
          git push
